[colors]
primary.background = "0x2b2e31"
primary.foreground = "0xd8dee9"

[colors.normal]
black   = "0x3b4252"
red     = "0xbf616a"
green   = "0xa3be8c"
yellow  = "0xebcb8b"
blue    = "0x81a1c1"
magenta = "0xb48ead"
cyan    = "0x88c0d0"
white   = "0xd8dee9"

[colors.bright]
black   = "0x4c566a"
red     = "0xdc7882"
green   = "0xb4d29b"
yellow  = "0xfadca0"
blue    = "0x96b9dc"
magenta = "0xcda5c3"
cyan    = "0xa0d7e6"
white   = "0xeceff4"

[window]
opacity = 0.80
